USER_TIMER1_CONFIG:
  TIMER1_ID_0:
    TIMER1_MODE_e: TIMER1_MODE_PERIODIC
    TIMER1_MODE_PERIODIC:
      TIMER1_GN_DATA_A: 1
      TIMER1_GN_DATA_B: 1000
    TIMER1_POL_e: TIMER1_POL_LOW
    TIMER1_CLK_e: TIMER1_CLK_MCCR
    TIMER1_CLK_MCCR:
      TIMER1_CLK_MCCR_e: TIMER1_CLK_MCCR_MCLK
      TIMER1_MCCR_DIV: 32
      TIMER1_PRESCALER: 1000
    TIMER1_PORT_e: TIMER1_PORT_IN
    TIMER1_INV_e: TIMER1_INV_OFF
    TIMER1_OVERFLOW_INTR: true
    TIMER1_ADCTRG_CTRL: false
    TIMER1_OPS_e: TIMER1_OPS_INTR
    TIMER1_OPS_INTR:
      TIMER1_OPS_INTR_PRIO: 0
