USER_TIMER1_CONFIG:
  TIMER1_ID_0:
    TIMER1_MODE_e: TIMER1_MODE_PERIODIC
    TIMER1_MODE_PERIODIC:
      TIMER1_GN_DATA_A: 5624
      TIMER1_GN_DATA_B: 1
    TIMER1_POL_e: TIMER1_POL_LOW
    TIMER1_CLK_e: TIMER1_CLK_PCLK
    TIMER1_CLK_PCLK:
      TIMER1_PCLK_DIV_e: TIMER1_PCLK_DIV_2
      TIMER1_PRESCALER: 0
    TIMER1_PORT_e: TIMER1_PORT_IN
    TIMER1_INV_e: TIMER1_INV_OFF
    TIMER1_OVERFLOW_INTR: false
    TIMER1_ADCTRG_CTRL: true
    TIMER1_ADCTRG_CTRL_ENABLE:
      TIMER1_ADCTRG_MODE_e: TIMER1_ADCTRG_MODE_NORMAL
    TIMER1_OPS_e: TIMER1_OPS_POLL
